# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $PATH
          echo "*******"
          echo "${PATH}"
          echo $MESSAGE}
          echo "*******"
          echo "${MESSAGE}"
          curl -X GET \
            --silent \
            -H 'content-type: application/json' \
            -H "x-api-key: ${NEWS_API_KEY}" \
            'http://newsapi.org/v2/top-headlines?country=us&category=business' | json_pp > news.json
          git config --global user.email "test@test.com"
          git config --global user.name "ehom"
          git add news.json
          git commit -m "Updated news headlines"
          git push
